'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.261
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Properties


	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits Global.System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = DirectCast(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings)

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property User() As String
			Get
				Return DirectCast(Me("User"), String)
			End Get
			Set
				Me("User") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property Password() As String
			Get
				Return DirectCast(Me("Password"), String)
			End Get
			Set
				Me("Password") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property Host() As String
			Get
				Return DirectCast(Me("Host"), String)
			End Get
			Set
				Me("Host") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		Public Property Registration() As Boolean
			Get
				Return CBool(Me("Registration"))
			End Get
			Set
				Me("Registration") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("0")> _
		Public Property Preferred() As Integer
			Get
				Return CInt(Me("Preferred"))
			End Get
			Set
				Me("Preferred") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("0")> _
		Public Property Allowed() As Integer
			Get
				Return CInt(Me("Allowed"))
			End Get
			Set
				Me("Allowed") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("-1")> _
		Public Property ConfigStatus() As Integer
			Get
				Return CInt(Me("ConfigStatus"))
			End Get
			Set
				Me("ConfigStatus") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property Input() As String
			Get
				Return DirectCast(Me("Input"), String)
			End Get
			Set
				Me("Input") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property Output() As String
			Get
				Return DirectCast(Me("Output"), String)
			End Get
			Set
				Me("Output") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property Ring() As String
			Get
				Return DirectCast(Me("Ring"), String)
			End Get
			Set
				Me("Ring") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("(Not Specified)")> _
		Public Property CallerIdNumber() As String
			Get
				Return DirectCast(Me("CallerIdNumber"), String)
			End Get
			Set
				Me("CallerIdNumber") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("SharpIAX")> _
		Public Property CallerIdName() As String
			Get
				Return DirectCast(Me("CallerIdName"), String)
			End Get
			Set
				Me("CallerIdName") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("0")> _
		Public Property ColorScheme() As Integer
			Get
				Return CInt(Me("ColorScheme"))
			End Get
			Set
				Me("ColorScheme") = value
			End Set
		End Property
	End Class
End Namespace
