DELIMITER ;;
DROP TRIGGER IF EXISTS nuevo_pedido;;
CREATE TRIGGER nuevo_pedido AFTER INSERT ON pedido
FOR EACH ROW BEGIN
DECLARE varIP CHAR(20);
DECLARE done INT DEFAULT 0;	
DECLARE c1 CURSOR FOR 
 SELECT ip from session
 WHERE TIME_TO_SEC(TIMEDIFF(NOW(),ttl))<600;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
	OPEN c1;
	REPEAT
	FETCH c1 INTO varIP;
	IF NOT done THEN
		SET @exec_var = sys_exec(CONCAT('echo ', NEW.id,' | nc ',varIP,' 6600 &'));
	END IF;
	UNTIL done END REPEAT;
	CLOSE c1;
END;
;;

DROP TRIGGER IF EXISTS cambio_pedido;;
CREATE TRIGGER cambio_pedido AFTER UPDATE ON pedido
FOR EACH ROW BEGIN
DECLARE varIP CHAR(20);
DECLARE done INT DEFAULT 0;	
DECLARE c1 CURSOR FOR 
 SELECT ip from session
 WHERE TIME_TO_SEC(TIMEDIFF(NOW(),ttl))<600;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
	OPEN c1;
	REPEAT
	FETCH c1 INTO varIP;
	IF NOT done THEN
		SET @exec_var = sys_exec(CONCAT('echo ', NEW.id,' | nc ',varIP,' 6600 &'));
	END IF;
	UNTIL done END REPEAT;
	CLOSE c1;
END;
;;

DROP TRIGGER IF EXISTS reclamo_pedido;;
CREATE TRIGGER reclamo_pedido AFTER INSERT ON reclamo_linea
FOR EACH ROW BEGIN
DECLARE varIP CHAR(20);
DECLARE done INT DEFAULT 0;	
DECLARE c1 CURSOR FOR 
 SELECT ip from session
 WHERE TIME_TO_SEC(TIMEDIFF(NOW(),ttl))<600;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
	OPEN c1;
	REPEAT
	FETCH c1 INTO varIP;
	IF NOT done THEN
		SET @exec_var = sys_exec(CONCAT('echo RECLAMO_LINEA,', NEW.id,' | nc ',varIP,' 6600 &'));
	END IF;
	UNTIL done END REPEAT;
	CLOSE c1;
END;
;;